Repository WishWesee/Client, pull requests merged in 2025-01, with the labels that each got.

#12 [feat/#11] 홈화면 UI 제작
  index.html
  src/assets/images/Home/BGMail.svg
  src/assets/images/Home/ImgIntroBG.svg
  src/assets/images/Home/SigninCardImg1.png
  src/assets/images/Home/SigninCardImg2.png
  src/assets/images/Home/SigninCardImg3.png
  src/components/button/Btn_Bottom_Next.tsx
  src/components/home/FeaturesGuide.tsx
  src/components/home/HomeLogin.tsx
  src/components/home/UsageCard.tsx
  src/components/home/UsageGuide.tsx
  src/constants/home.ts
  src/hooks/Media.tsx
  src/hooks/useMediaQuery.ts
  src/hooks/useWMediaQuery.ts
  src/index.css
  src/pages/Home.tsx
  src/styles/Layout.ts
  src/styles/essentialComponents/button/ButtonBottomNextStyle.ts
  src/styles/home/FeaturesGuideStyle.ts
  src/styles/home/HomeLoginStyle.ts
  src/styles/home/UsageGuideStyle.ts
  vite.config.ts
Labels: ✨ Feature, 🎨 Html&css

#18 [feat/#15] Box, TimeTable, 참석 여부 조사 체크 컴포넌트 제작
  src/Router.tsx
  src/api/index.ts
  src/components/invite/ContentTextBox.tsx
  src/components/invite/ContentTimeTable.tsx
  src/components/invite/ContentWrap.tsx
  src/components/invite/InviteBottom.tsx
  src/components/invite/ReviewWrap.tsx
  src/constants/invite.ts
  src/pages/InvitationDetailPage.tsx
  src/styles/invite/ContentBodyStyle.ts
  src/styles/invite/ContentWrapStyle.ts
  src/styles/invite/InvitationDetailPageStyle.ts
  src/styles/invite/InviteBottomStyle.ts
  src/styles/invite/ReviewWrapStyle.ts
  src/types/invite.ts
  src/utils/formatVoteDateTime.ts
Labels: ✨ Feature, 🎨 Html&css

#19 [feat/#15] 폰트 스타일 추가
  src/components/invite/ContentWrap.tsx
  src/types/invite.ts
Labels: ✨ Feature, 🎨 Html&css

#21 [feat/#13] 구글로그인, 내초대장 페이지 API 연결 및 수정
  package-lock.json
  package.json
  src/Router.tsx
  src/api/login/profile.ts
  src/api/myinvitation/myinvitationData.ts
  src/assets/icons/화면GUI_Line/2020/Arrow_Left.tsx
  src/assets/icons/화면GUI_Line/2828/Arrow_Right.svg
  src/assets/icons/화면GUI_Line/2828/Arrow_Right.tsx
  src/assets/images/ChoiceCard/Birthday1.svg
  src/assets/images/ChoiceCard/Birthday2.svg
  src/assets/images/ChoiceCard/LastOfYear1.svg
  src/assets/images/ChoiceCard/LastOfYear2.svg
  src/assets/images/ChoiceCard/travel1.svg
  src/assets/테스트이미지/TestImage.svg
  src/components/ImgContentCut.tsx
  src/components/button/Btn_Bottom_Next.tsx
  src/components/choiceCard/HorizontalSB.tsx
  src/components/choiceCard/Modal.tsx
  src/components/choiceCard/Rectangle.tsx
  src/components/choiceCard/Wrap.tsx
  src/components/login/FeatureBoxEmpty.tsx
  src/components/login/GoogleLogin.tsx
  src/components/login/LoginSection.tsx
  src/components/myInvitation/LetterContainer.tsx
  src/components/myInvitation/MenuContainer.tsx
  src/components/myInvitation/ReviewModal.tsx
  src/components/myInvitation/SlideBar.tsx
  src/components/myInvitation/TestImage.tsx
  src/components/myInvitation/TestImage2.svg
  src/components/top/Top_Header.tsx
  src/components/top/Top_reactNB.tsx
  src/constants/choiceCard/Wrap.ts
  src/constants/essentialComponents/Comp_Top.ts
  src/constants/myInvitation/MyInvitation.ts
  src/pages/ChoiceCard.tsx
  src/pages/LoginScreen.tsx
  src/pages/MyInvitation.tsx
  src/store/useChoiceStore.ts
  src/styles/choiceCard/ChoiceCardStyle.ts
  src/styles/choiceCard/HorizontalSBStyle.ts
  src/styles/choiceCard/ImgContentCut.ts
  src/styles/choiceCard/ModalStyle.ts
  src/styles/choiceCard/RectangleStyle.ts
  src/styles/choiceCard/WrapStyle.ts
  src/styles/essentialComponents/button/ButtonBottomNextStyle.ts
  src/styles/essentialComponents/top/TopHeaderStyle.ts
  src/styles/essentialComponents/top/TopReactNBStyles.ts
  src/styles/login/ColumnComponentStyle.ts
  src/styles/login/FeatureBoxComponentStyle.ts
  src/styles/login/GreetingMessageComponentStyle.ts
  src/styles/login/LoginScreenPageStyle.ts
  src/styles/login/LoginSectionComponentStyle.ts
  src/styles/myInvitation/MenuContainerStyle.ts
  src/styles/myInvitation/MyInvitationContainerStyle.ts
  src/styles/myInvitation/MyInvitationPageStyle.ts
  src/styles/myInvitation/ReviewModalStyle.ts
  src/styles/myInvitation/SlideBarStyle.ts
Labels: 🎨 Html&css, 📬 API

#24 [feat/#11] 홈화면 로그인 버튼 추가
  src/components/home/HomeLogin.tsx
  src/components/home/UsageGuide.tsx
Labels: ✨ Feature, 🎨 Html&css

#26 [feat/#15] 초대장 줄바꿈 및 타입 추가
  package-lock.json
  src/components/invite/CheckContentWrap.tsx
  src/components/invite/ContentWrap.tsx
  src/styles/invite/ContentBodyStyle.ts
  src/styles/invite/ContentWrapStyle.ts
  src/types/invite.ts
Labels: ✨ Feature, 🎨 Html&css

#27 [feat/#15] 초대장 조회 에러처리 추가
  src/api/attendanceVote/getAttendance.ts
  src/api/invitation/getFeedback.ts
  src/api/invitation/getReceivedInvitation.ts
  src/api/invitation/getSentInvitation.ts
  src/components/invite/ComingWrap.tsx
  src/components/invite/ReviewWrap.tsx
  src/pages/InvitationDetailPage.tsx
  src/pages/ReceivedInvitationListPage.tsx
  src/pages/SentInvitationListPage.tsx
Labels: ✨ Feature
