Repository WishWesee/Client, pull requests merged in 2025-02, with the labels that each got.

#28 [feat/#15] 초대장 로그인 조건 수정
  src/components/invite/ContentWrap.tsx
  src/pages/InvitationDetailPage.tsx
  src/types/invite.ts
Labels: ✨ Feature

#29 [feat/#13] 로컬스토리 토큰 세팅(임시) 및 로그아웃 회원탈퇴 모달 추가
  package-lock.json
  package.json
  src/api/index.ts
  src/api/login/deleteAccount.ts
  src/api/login/logOut.ts
  src/api/login/profile.ts
  src/api/myinvitation/myinvitationData.ts
  src/api/myinvitation/reviewCheck.ts
  src/assets/icons/화면GUI_Line/2828/Arrow_Right.tsx
  src/components/home/HomeLogin.tsx
  src/components/login/GoogleLogin.tsx
  src/components/login/LoginSection.tsx
  src/components/myInvitation/LetterContainer.tsx
  src/components/myInvitation/MenuContainer.tsx
  src/components/myInvitation/ReviewModal.tsx
  src/components/top/DeleteAccountModal.tsx
  src/components/top/Top_Header.tsx
  src/constants/login/loginScreen.ts
  src/pages/MyInvitation.tsx
  src/styles/ModalStyle.ts
  src/styles/essentialComponents/top/TopHeaderStyle.ts
Labels: 🎨 Html&css, 📬 API

#31 [feat/#11] 로그인 상태에 따라 홈화면 수정
  FETCH_HEAD
  src/pages/Home.tsx
Labels: ✨ Feature

#32 [fix] 홈화면 로그인 조건 수정
  src/components/invite/ComingWrap.tsx
  src/components/top/Top_Header.tsx
  src/pages/Home.tsx
  src/store/useAuthStore.ts
Labels: 🐞 BugFix

#33 [feat/#13] 카드 사진추가 비로그인시 로직 추가 및 로그아웃 세팅 변경(임시)
  src/components/choiceCard/Modal.tsx
  src/components/login/GoogleLogin.tsx
  src/components/top/Top_Header.tsx
  src/pages/ChoiceCard.tsx
Labels: ✨ Feature, 🐞 BugFix

#35 [fix/#34] 로그인 리다이렉트 페이지 추가
  src/Router.tsx
  src/api/index.ts
  src/components/LoginScreen.tsx
  src/components/Test.tsx
  src/components/invite/SaveWrap.tsx
  src/components/invite/ShareWrap.tsx
  src/components/login/LoginBoxColumn.tsx
  src/components/login/LoginSection.tsx
  src/components/top/Top_Header.tsx
  src/pages/Home.tsx
  src/pages/Redirect.tsx
  src/store/useNavigateStore.ts
Labels: ✨ Feature, 🐞 BugFix

#36 [fix/#34] 도메인 링크 수정 및 로그인 쿠키 확인
  index.html
  package-lock.json
  src/api/index.ts
  src/components/invite/KakaoWrap.tsx
  src/components/invite/ShareWrap.tsx
  src/components/shareSNS/ShareKakao.tsx
  src/components/top/Top_Header.tsx
  src/pages/ChoiceCard.tsx
  src/pages/Redirect.tsx
Labels: ✨ Feature

#37 [feat/#13] 로그인 토큰설정 및 불러오기 세팅
  src/api/index.ts
  src/api/login/deleteAccount.ts
  src/api/login/logOut.ts
  src/components/top/Top_Header.tsx
  src/constants/myInvitation/MyInvitation.ts
  src/pages/ChoiceCard.tsx
  src/pages/MyInvitation.tsx
Labels: ✨ Feature, 🐞 BugFix, 📬 API

#38 [fix/#13] 내 아이콘 위치 조정 및 로그아웃/탈퇴 수정
  src/api/login/logOut.ts
  src/components/top/Top_Header.tsx
Labels: 🐞 BugFix

#39 Feat/#5 write page UI
  src/api/invitation/postInvitation.ts
  src/components/invitationWrite/CheckComponent.tsx
  src/components/invitationWrite/InvitationWriteComponent.tsx
  src/components/invite/CheckContentWrap.tsx
  src/hooks/write/usePostInvitation.ts
  src/pages/ChoiceCard.tsx
  src/store/invitation.ts
  src/store/useChoiceStore.ts
  src/types/invitation.ts
  src/types/invite.ts
  src/utils/calendar/formatCustomDateFromDate.ts
Labels: ✨ Feature, 📬 API

#41 Fix/#40 작성 qa 수정
  src/api/invitation/postInvitation.ts
  src/assets/icons/화면GUI_Full/2424_Activate/color/ActiveBox0.svg
  src/assets/icons/화면GUI_Full/2424_Activate/color/ActiveBox1.svg
  src/assets/icons/화면GUI_Full/2424_Activate/color/ActiveBox2.svg
  src/assets/icons/화면GUI_Full/2424_Activate/color/ActiveBox3.svg
  src/assets/icons/화면GUI_Full/2424_Activate/color/ActiveBox4.svg
  src/assets/icons/화면GUI_Full/2424_Activate/color/ActiveBox5.svg
  src/assets/icons/화면GUI_Full/2424_Activate/color/ActiveBox6.svg
  src/assets/icons/화면GUI_Full/2424_Default/color/box0.svg
  src/assets/icons/화면GUI_Full/2424_Default/color/box1.svg
  src/assets/icons/화면GUI_Full/2424_Default/color/box2.svg
  src/assets/icons/화면GUI_Full/2424_Default/color/box3.svg
  src/assets/icons/화면GUI_Full/2424_Default/color/box4.svg
  src/assets/icons/화면GUI_Full/2424_Default/color/box5.svg
  src/assets/icons/화면GUI_Full/2424_Default/color/box6.svg
  src/components/invitationWrite/InvitationWriteBottomButton.tsx
  src/components/invitationWrite/InvitationWriteComponent.tsx
  src/components/invitationWrite/InvitationWriteLocation.tsx
  src/components/invitationWrite/InvitationWriteToolBar.tsx
  src/components/invitationWrite/blocks/InvitationWriteBoxComponent.tsx
  src/components/invitationWrite/blocks/InvitationWritePhotoComponent.tsx
  src/components/invitationWrite/blocks/InvitationWriteTextComponent.tsx
  src/components/invitationWrite/blocks/InvitationWriteTimeItem.tsx
  src/components/invitationWrite/blocks/InvitationWriteTimeTableComponent.tsx
  src/components/invitationWrite/calendar/InvitationWriteTimeTableModal.tsx
  src/components/invitationWrite/calendar/InvitationWriteVoteComponent.tsx
  src/components/invite/CheckContentWrap.tsx
  src/components/modal/CheckModal.tsx
  src/constants/invitationWrite/toolBar.tsx
  src/hooks/write/usePostInvitation.ts
  src/pages/InvitationWritePage.tsx
  src/store/invitation.ts
  src/styles/common/checkModal.ts
  src/styles/invitationWrite/blocks/invitationWriteBoxComponent.ts
  src/styles/invitationWrite/blocks/invitationWriteDividerComponentStyle.ts
  src/styles/invitationWrite/blocks/invitationWriteTimeItem.ts
  src/styles/invitationWrite/blocks/invitationWriteTimeTableComponent.ts
  src/styles/invitationWrite/invitationWriteToolBar.ts
  src/types/invitation.ts
Labels: 🐞 BugFix

#42 Fix/#40 작성 qa 수정
  src/components/invitationWrite/InvitationWriteCalendar.tsx
  src/components/invitationWrite/InvitationWriteComponent.tsx
  src/components/invitationWrite/InvitationWriteToolBar.tsx
  src/components/invitationWrite/blocks/InvitationWriteBoxComponent.tsx
  src/components/invitationWrite/blocks/InvitationWriteTextComponent.tsx
  src/components/invitationWrite/blocks/InvitationWriteTimeItem.tsx
  src/components/invitationWrite/blocks/InvitationWriteTimeTableComponent.tsx
  src/components/invitationWrite/calendar/InvitationWriteVoteComponent.tsx
  src/components/invitationWrite/calendar/InvitationWriteVoteItem.tsx
  src/constants/invitationWrite/toolBar.tsx
  src/store/invitation.ts
  src/styles/invitationWrite/blocks/invitationWriteBoxComponent.ts
  src/styles/invitationWrite/calendar/invitationWriteVoteComponentStyle.ts
Labels: 🐞 BugFix

#43 [fix/#34] 초대장 열람, 완성 페이지 QA 수정
  src/components/invitationWrite/CheckComponent.tsx
  src/components/invite/CheckContentWrap.tsx
  src/components/invite/ComingWrap.tsx
  src/components/invite/ContentWrap.tsx
  src/components/invite/VotePersonModal.tsx
  src/pages/InvitationDetailPage.tsx
  src/pages/InvitationWritePage.tsx
  src/styles/Layout.ts
  src/styles/essentialComponents/top/TopHeaderStyle.ts
  src/styles/invitationWrite/invitationWritePage.ts
  src/styles/invite/ContentWrapStyle.ts
  src/styles/invite/InvitationDetailPageStyle.ts
  src/types/invitation.ts
  src/utils/formatVoteDateTime.ts
Labels: 🐞 BugFix

#44 [fix/#34] 스크롤 애니메이션 수정
  src/components/invitationWrite/CheckComponent.tsx
  src/pages/InvitationDetailPage.tsx
  src/styles/invite/InvitationDetailPageStyle.ts
Labels: 🐞 BugFix

#45 [feat/#13] 토큰 리프레시 세팅 및 카드 세팅 변경
  src/api/index.ts
  src/assets/images/ChoiceCard/Birthday1.png
  src/assets/images/ChoiceCard/Birthday1.svg
  src/assets/images/ChoiceCard/Birthday2.png
  src/assets/images/ChoiceCard/Birthday2.svg
  src/assets/images/ChoiceCard/LastOfYear1.png
  src/assets/images/ChoiceCard/LastOfYear1.svg
  src/assets/images/ChoiceCard/LastOfYear2.png
  src/assets/images/ChoiceCard/LastOfYear2.svg
  src/assets/images/ChoiceCard/Travel.png
  src/assets/images/ChoiceCard/travel1.svg
  src/pages/ChoiceCard.tsx
  src/styles/choiceCard/ChoiceCardStyle.ts
Labels: 🐞 BugFix, 📬 API

#46 [Fix] save
  src/components/invitationWrite/CheckComponent.tsx
  src/components/invitationWrite/InvitationWriteComponent.tsx
  src/pages/InvitationWritePage.tsx
  src/store/invitation.ts
  src/types/invitation.ts
Labels: 🐞 BugFix

#47 [fix/#34] 완성 페이지에 참석 여부 조사 필드 추가
  src/components/invitationWrite/CheckComponent.tsx
  src/pages/InvitationDetailPage.tsx
Labels: 🐞 BugFix

#48 [fix/#13] 회원탈퇴 api 변경 및 로그아웃시 My 카드 비활성화
  src/api/login/deleteAccount.ts
  src/pages/ChoiceCard.tsx
Labels: 🐞 BugFix

#49 Fix/# font
  src/components/invitationWrite/InvitationWriteComponent.tsx
  src/components/invitationWrite/blocks/InvitationWriteTextComponent.tsx
  src/pages/InvitationWritePage.tsx
Labels: 🐞 BugFix
